services:
  fbf-phv3:
    build: .
    image: rodekruis510/typhoonmodel
    ports:
      - "587:587"
    #container_name: ibf
    #env_file:
    #  - secrets
    environment:
      - CONDA_ENV=climada_env
    volumes:
      - './IBF-Typhoon-model:/home/fbf'  
      #- $TYPHOONMODEL_OUTPUT:/home/fbf
    #command: run-typhoon-model  --typhoonname="RAI" --remote_directory='20211214000000'
    command: run-typhoon-model
